#!/bin/bash
sed -i "s/external_url '.*'/external_url 'http:\/\/$(/usr/local/bin/oc-metadata ID).pub.cloud.scaleway.com'/g" /etc/gitlab/gitlab.rb
gitlab-ctl reconfigure &> /dev/null
gitlab-ctl reconfigure &> /dev/null
sed -i s/gitlab-reconfigure.*//g /etc/rc.local
