#!/bin/bash

cat <<EOF
To continue the installation, open http://$(/usr/local/bin/oc-metadata --cached PUBLIC_IP_ADDRESS)/ in your browser. Default login/password is root/5iveL!fe
Getting started with GitLab on C1: https://www.scaleway.com/docs/how-to-use-the-gitlab-instant-apps.
You can hide this message on the next connection by deleting the $0 file.
EOF
