#!/bin/bash

cat <<EOF
Configure and start GitLab by running the following command:

sudo gitlab-ctl reconfigure
EOF

cat <<EOF
You can hide this message on the next connection by deleting the $0 file.
EOF
